openapi: 3.0.0
info:
  title: Song Similarity Analyzer API
  version: 1.0.0
  description: API for comparing Professor Remember's song with the top 5 songs of a provided singer.
paths:
  /compare-professor-song:
    post:
      summary: Compare Professor Remember's song with top 5 songs of a provided singer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                singer_name:
                  type: string
                  description: Name of the singer whose top 5 songs will be compared
                professor_song_url:
                  type: string
                  description: URL of Professor Remember's song to compare
                professor_song_lyrics:
                  type: string
                  description: Lyrics of Professor Remember's song to compare
              required:
                - singer_name
                - professor_song_url
                - professor_song_lyrics
      responses:
        '200':
          description: Comparison results
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    artist_song:
                      type: string
                      description: Song name by the artist
                    professor_song:
                      type: string
                      description: Song name by Professor Remember
                    similarity:
                      type: number
                      format: float
                      description: Similarity score between the two songs
        '400':
          description: Bad request
        '404':
          description: Not found
  /health:
    get:
      summary: Health check endpoint
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Health status
